import { createHtmlReport } from 'axe-html-reporter';
import { expect, test } from 'test/fixtures/axe';

test.describe('workbench', () => {
    test.skip('should not have accessibility issues', async ({
        dataBuilder,
        factories,
        makeAxeBuilder
    }, testInfo) => {
        await dataBuilder.overview.dataModelsTabButton.click();

        // Create a new data model and open it to view the workbench
        // Create test data
        const testDataModel = factories.dataModel.createErDataModel();
        // Create a new data model
        await dataBuilder.overview.dataModelsTab.createErDataModel(testDataModel);
        // Search for the data model and open it
        await dataBuilder.overview.dataModelsTab.search(testDataModel.name);
        await dataBuilder.overview.dataModelsTab.dataModelCard(testDataModel.technicalName).open();

        // Wait for the SVG element generated by Vue Flow to be rendered
        // so we know the canvas has been loaded
        await expect(dataBuilder.workbench.canvas.root).toBeVisible();

        const accessibilityScanResults = await makeAxeBuilder().analyze();

        await testInfo.attach('accessibility-scan-results', {
            body: JSON.stringify(accessibilityScanResults, null, 2),
            contentType: 'application/json'
        });

        createHtmlReport({
            results: accessibilityScanResults,
            options: {
                outputDir: './test-results/accessibility-report',
                reportFileName: 'workbench.html',
                projectKey: 'Data Builder'
            }
        });

        expect(accessibilityScanResults.violations.length).toEqual(0);
    });
});
