/**
 * Tests for import-export round-trip integrity
 */

import type { Download } from '@playwright/test';
import * as yaml from 'js-yaml';
import { join } from 'path';
import { expect, test } from 'test/fixtures/base';

async function readDownloadedFile(download: Download): Promise<string> {
    const fileBuffer = await download.createReadStream();
    const chunks: Buffer[] = [];

    for await (const chunk of fileBuffer) {
        chunks.push(Buffer.from(chunk as Uint8Array));
    }

    return Buffer.concat(chunks).toString('utf8');
}

async function readFixtureFile(filePath: string): Promise<string> {
    const fs = await import('fs/promises');
    return await fs.readFile(filePath, 'utf8');
}

/**
 * Normalizes YAML content by replacing auto-generated fields with placeholders
 * while validating they have the correct format
 */
function normalizeYamlContent(content: string): string {
    // Parse YAML to object
    const data = yaml.load(content) as Record<string, unknown>;

    // Regex patterns for validation
    const ISO_DATE_PATTERN = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/;
    // Generated IDs are UUIDs, and some values include prefixes like ENTITY.<uuid>.
    const AUTO_ID_PATTERN = /^[A-Za-z0-9._-]+$/;

    // Recursively normalize auto-generated fields
    function normalizeAutoGeneratedFields(obj: unknown): unknown {
        if (obj === null || typeof obj !== 'object') {
            return obj;
        }

        if (Array.isArray(obj)) {
            return obj.map(normalizeAutoGeneratedFields);
        }

        const normalized: Record<string, unknown> = {};

        for (const [key, value] of Object.entries(obj)) {
            // Handle auto-generated timestamp fields
            if (key === 'created' || key === 'updated') {
                // js-yaml can parse dates as Date objects or strings
                // Handle both cases
                let dateString: string;

                if (value instanceof Date) {
                    // Convert Date object to ISO string
                    dateString = value.toISOString();
                } else if (typeof value === 'string') {
                    dateString = value;
                } else {
                    throw new Error(
                        `${key} field is invalid. ` +
                            `Expected ISO date string or Date object, but got: ${JSON.stringify(value)} (type: ${typeof value})`
                    );
                }

                // Validate the date string format
                if (dateString.length > 0 && ISO_DATE_PATTERN.test(dateString)) {
                    normalized[key] = 'NORMALIZED_TIMESTAMP';
                } else {
                    throw new Error(`${key} field has invalid ISO date format: ${dateString}`);
                }
            }
            // Handle auto-generated ID fields (id, canvasId, uuid, elementUUID)
            else if (
                key === 'id' ||
                key === 'canvasId' ||
                key === 'uuid' ||
                key === 'elementUUID'
            ) {
                // Validate it's a non-empty generated ID string
                if (typeof value === 'string' && value.length > 0) {
                    expect(value).toMatch(AUTO_ID_PATTERN);
                    normalized[key] = 'NORMALIZED_ID';
                } else {
                    throw new Error(
                        `${key} field is empty or invalid. ` +
                            `Expected non-empty generated ID string, but got: ${JSON.stringify(value)} (type: ${typeof value})`
                    );
                }
            }
            // All other fields: recursively process
            else {
                normalized[key] = normalizeAutoGeneratedFields(value);
            }
        }

        return normalized;
    }

    const normalized = normalizeAutoGeneratedFields(data);

    // Convert back to YAML with consistent formatting
    const yamlString = yaml.dump(normalized, {
        indent: 4,
        lineWidth: -1,
        noRefs: true
    });

    // Ensure we return a string
    if (typeof yamlString !== 'string') {
        throw new Error('Failed to convert normalized data to YAML string');
    }

    return yamlString;
}

test.beforeEach(async ({ dataBuilder }) => {
    await dataBuilder.overview.dataModelsTabButton.click();
});

test('import-export round-trip preserves data', async ({ dataBuilder }) => {
    test.slow();

    const filePath = join(process.cwd(), 'test-data/visitor.yaml');

    // Import
    await dataBuilder.page
        .getByTestId('DB-ModelsList-IxOverview-importsplitbutton-IxSplitButton-OpenMenu')
        .click();

    await dataBuilder.page.getByText('Import from Export').click();
    await dataBuilder.overview.page.waitForTimeout(2000);

    const fileInput = dataBuilder.page.locator(
        '[data-testid="DB-ModelsList-CreateCopyModal-v-file-input-Input"] input[type="file"]'
    );
    await fileInput.setInputFiles(filePath);

    await dataBuilder.page.getByRole('textbox', { name: 'New name' }).fill('bench-w0t1');

    await dataBuilder.page.getByRole('textbox', { name: 'New technical name' }).click();

    await dataBuilder.page
        .getByTestId('DB-ModelsList-CreateCopyModal-CreateCopy-IxButton-root')
        .click();

    await dataBuilder.page.waitForTimeout(2000);

    await dataBuilder.workbench.deploymentToolbar.moveBackToOverviewButton.click();

    await dataBuilder.overview.dataModelsTab.search('bench-w0t1');

    // Verify the imported model is visible
    await expect(dataBuilder.page.getByText('bench-w0t1')).toBeVisible();

    // Export
    await dataBuilder.page
        .getByTestId(
            'DB-ModelsList-ListRow-bench-w0t1-IxOverviewCard-menu-button-IxIconButton-root'
        )
        .click();

    const downloadPromise = dataBuilder.page.waitForEvent('download');

    await dataBuilder.page.getByTestId('DB-ModelsList-MenuItem-Export-IxMenuListItem-root').click();

    const download = await downloadPromise;

    // Compare - normalize both contents before comparison
    const exportedContent = await readDownloadedFile(download);
    const originalContent = await readFixtureFile(filePath);

    const normalizedExported = normalizeYamlContent(exportedContent);
    const normalizedOriginal = normalizeYamlContent(originalContent);

    expect(normalizedExported).toBe(normalizedOriginal);
});
